### ISSUE TITLE
Remove non-folder icons from this theme?

### ISSUE THREAD

**Issue by johnraff** [BunsenLabs/bunsen-faenza-icon-theme#2]
Posted by @hhh

> I'm thinking that it would be better to make Faenza-Bunsen and Faenza-Bunsen-Dark inherit Faenza and Faenza-Dark, and set faenza-icon-theme as a dependency of bunsen-faenza-icon-theme, so we'll just have folder icons in our theme and the rest will be provided by Faenza.

This sounds sensible to me, but does anyone else have thoughts on it?

**Comment by johnraff** [comment]
@hhhorb Here's the new icon theme: https://dl.dropboxusercontent.com/u/10808732/Faenza-Bunsen-new.tar.gz
I've taken out all the icons that are not different in Faenza-Bunsen from Faenza (checked with diff -rq), added decolorized versions of the six that the .desktop files use and edited index.theme to inherit Faenza. The deb package will depend on Faenza.

Does it look OK at a quick glance? I'll package it up tomorrow and install it on my VM to see how it goes.
The one remaining issue is that the Faenza _web-browser_ icon is not all that great, colorized or not. Can you think of any alternative we could put in?

**Comment by hhhorb** [comment]
Wow, that's fantastic! This inherits Faenza, but for the default BL setup we need it to inherit Faenza-Dark. Not sure how we want to handle that, two icon sets identical except for the index file? Seems too redundant.

For the web-browser icon, I prefer /categories/24/applications-internet.png which we could desaturate...
https://forums.bunsenlabs.org/viewtopic.php?pid=5764#p5764

Thanks for covering my slacking ass, I have some personal stuff distracting me as usual.

**Comment by johnraff** [comment]
> For the web-browser icon, I prefer /categories/24/applications-internet.png which we could desaturate...
> https://forums.bunsenlabs.org/viewtopic.php?pid=5764#p5764

But two posts later you found that when desaturated "the browser icon doesn't look like much of anything..."

Could it have its contrast boosted or something? It would need to be something that can be automated with imagemagick - I don't really feel like doing each one manually with Gimp.

I ran out of time yesterday but will have a look at the Dark set today, and see if there's a way to use inheritance to avoid duplicating image files.

**Comment by johnraff** [comment]
Actually imagemagick did a better job of desaturating than tint2 (`convert -colorspace Gray`):
<a href='http://postimage.org/' target='_blank'><img src='http://s11.postimg.org/t81tnn46n/2015_11_30_13_17_12_scrot.png' border='0' alt="2015 11 30 13 17 12 scrot" /></a>
That might be OK for the browser icon?

**Comment by hhhorb** [comment]
Yes, that's what I was hoping. GIMP's desaturate dialog also has options that alter the brightness/contrast which might improve legibility even more, but that looks way better and IMO looks better than the compass. Nice!

**Comment by johnraff** [comment]
**bunsen-faenza-icon-theme 8.1-1** pushed to GitHub.
It's _much_ smaller now, ~750KB instead of 24MB, although of course it depends on Faenza.
The Dark theme inherits Faenza-Dark and has symlinks to the grey folder icons in Faenza-Bunsen so it hardly contains anything.

It seemed to work OK whn installed on a VM but there might be subtle bugs...

**Comment by hhhorb** [comment]
I'm using Dark now with no problems yet, fantastic!

Keep this issue open for a few days while we keep an eye out, please. Thanks, great work!

**Comment by johnraff** [comment]
Just after uploading, I thought of a cleaner way of sharing the grey icons between F-BL & F-Dark-BL without all those messy symlinks: a _Faenza-Bunsen-common_ theme that both can inherit. I'm just about to give it a try, but it won't be an urgent upgrade when it comes - functionality will stay the same.

Also we've got an "extras" directory in each theme, a legacy from #!. They seem to be icons for a few random programs. As it is those icons can't be used by a theme because they aren't indexed - only direct links will work. I'll check if they aren't duplicating something already in Faenza, and if they look at all meaningful I'll distribute them round the various directories where they should be. Otherwise delete.

**Comment by hhhorb** [comment]
> They seem to be icons for a few random programs.

Put them in applications if they're worthwhile, otherwise +1 delete.

Thanks again for your work on this, JR.

**Comment by johnraff** [comment]
**8.1.1-2** pushed. I think this way, using inheritance, is much cleaner than having symlinks all over the place, and makes it easier to drop in a couple of extra icons if we want to.

Most of those "extras" icons were duplicates of what's in Faenza - only some Liferea status icons remained, which I added to the respective status/22 directories.

It seems to install and work OK but it's hardly been exhaustively tested so far.
