### ISSUE TITLE
start-here icon shows the Ubuntu logo

### ISSUE THREAD

**Issue by o9000** [BunsenLabs/bunsen-faenza-icon-theme#3]
`/usr/share/icons/Faenza/places/32/start-here.png` is a link to `distributor-logo-ubuntu.png` instead of the Debian logo, or even better, the BunsenLabs logo.

Also `/usr/share/icons/Faenza-Dark/places/32/start-here.png` points to the Ubuntu logo, and I suspect that there might be similar links in the other color variants of the Faenza icon theme.

**Comment by johnraff** [comment]
**bunsen-faenza-icon-theme** inherits Faenza and Faenza-Dark for a lot of its icons. We could add custom _start-here_ icons to override the Faenza ones, if the developers generally thought it was worthwhile doing. I'll check some other opinions.

**Comment by johnraff** [comment]
Fixed in 2016: https://github.com/BunsenLabs/bunsen-faenza-icon-theme/commit/04ddb7c10e6d5ac160fd4242f366d8e21473b4f0
